image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/gradle:7.2-jdk11

stages:
  - build
  - test
#  - changelog

before_script:
  - ./gradlew markdownToHtml deleteCopiedChangelog

build:
  stage: build
  script:
    - ./gradlew build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - if: $CI_COMMIT_BRANCH
      when: always

lsif:
  stage: build
  needs: []
  before_script: []
  allow_failure: true
  script:
    - curl -fLo coursier https://git.io/coursier-cli
    - chmod +x coursier
    - ./coursier bootstrap --standalone -o lsif-java com.sourcegraph:lsif-java_2.13:0.6.9
    - ./gradlew build
    - ./lsif-java index-semanticdb build/semanticdb-targetroot/
  artifacts:
    reports:
      lsif: dump.lsif

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew verifyPlugin
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: on_success
    - if: $CI_COMMIT_BRANCH
      when: on_success

check_changelog:
  stage: test
  needs: []
  before_script: []
  script:
    - export COMMIT_MESSAGE=`git log --format=%B --no-merges -1` # Hack for merged results
    - echo $COMMIT_MESSAGE
    - "[[ \"$COMMIT_MESSAGE\" == *\"Changelog: Added\"* ]] || [[ \"$COMMIT_MESSAGE\" == *\"Changelog: Changed\"* ]] || [[ \"$COMMIT_MESSAGE\" == *\"Changelog: Fixed\"* ]] || [[ \"$COMMIT_MESSAGE\" == *\"Changelog: Removed\"* ]] || [[ \"$COMMIT_MESSAGE\" == *\"changelog-ignored\"* ]] || exit 2"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: always
      allow_failure: false
    - if: $CI_COMMIT_BRANCH
      when: always
      allow_failure: true

#changelog:
#  stage: changelog
#  script:
#    - ./gradlew publishChangelog -Dproject_id="$CI_PROJECT_ID" -Dtoken="$CI_JOB_TOKEN" -Dtoken_type="Private-Token" -Dtag="$CI_COMMIT_TAG"
#  only:
#    - tags